# Generated by Django 5.1.1 on 2025-04-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_farm_field_crop_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('farm_manager', 'Farm Manager'), ('field_worker', 'Field Worker')], max_length=20),
        ),
    ]
